-- PostgreSQL mirror of ../001_initial.sql (same tables, columns, constraints).
-- Type mapping: TEXT → TEXT COLLATE "C" (byte order, as SQLite BINARY), so
-- ORDER BY on ids / ISO timestamps sorts identically; REAL → DOUBLE PRECISION;
-- INTEGER PRIMARY KEY AUTOINCREMENT → BIGINT identity (monotonic, never reused).

CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY NOT NULL,
    applied_at TEXT NOT NULL,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS observation_packets (
    packet_id TEXT COLLATE "C" PRIMARY KEY NOT NULL,
    site_ref_id TEXT COLLATE "C" NOT NULL,
    city TEXT COLLATE "C" NOT NULL,
    workflow_state TEXT COLLATE "C" NOT NULL,
    revision INTEGER NOT NULL CHECK (revision >= 1),
    document_json TEXT NOT NULL,
    flags_rules_version TEXT COLLATE "C",
    created_at TEXT COLLATE "C" NOT NULL,
    updated_at TEXT COLLATE "C" NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_packets_site_ref
    ON observation_packets (site_ref_id);

CREATE INDEX IF NOT EXISTS idx_packets_workflow
    ON observation_packets (workflow_state);

-- Append-only provenance. No UPDATE/DELETE API in application.
CREATE TABLE IF NOT EXISTS provenance_events (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT COLLATE "C" NOT NULL UNIQUE,
    packet_id TEXT COLLATE "C" NOT NULL,
    at TEXT COLLATE "C" NOT NULL,
    actor_type TEXT COLLATE "C" NOT NULL,
    actor_id TEXT COLLATE "C" NOT NULL,
    action TEXT COLLATE "C" NOT NULL,
    before_json TEXT,
    after_json TEXT,
    model_id TEXT COLLATE "C",
    prompt_version TEXT COLLATE "C",
    rule_engine_version TEXT COLLATE "C",
    FOREIGN KEY (packet_id) REFERENCES observation_packets (packet_id)
);

CREATE INDEX IF NOT EXISTS idx_provenance_packet_seq
    ON provenance_events (packet_id, seq);
